[libraries]
errorpronePlugin    = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version = "5.0.0" }
errorproneCore      = { module = "com.google.errorprone:error_prone_core", version = "2.47.0" }

jspecify            = { module = "org.jspecify:jspecify", version = "1.0.0" }

nullaway            = { module = "com.uber.nullaway:nullaway", version = "0.13.1" }

sonarPlugin         = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version = "7.2.2.6593" }

spotlessPlugin      = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "8.2.1" }

